### PR TITLE
Async/Await refactor, improve Readme...

### PR DESCRIPTION
**Pull request by heiso**
Async/Await refactor
Improve Readme
Remove unused dependencies
Add npm badges
Add travis.yml

You can [add your repository to travis CI here](https://travis-ci.org/profile/aaronshaf)

### CODE REVIEW

**Comment by heiso** [comment]
Hey @aaronshaf !
I'm currently using you tool and as I needed to add some features I decided to begin with some improvements on the code itself :)

Feel free to review/comment ;)

Nice tool by the way, helped a lot !

**Comment by aaronshaf** [comment]
Perhaps we could use prettier to format it?

**Comment by heiso** [comment]
Yes why not :)

**Comment by heiso** [comment]
Or maybe this one https://standardjs.com/ @aaronshaf

**Pull request merged**
